postgres:
  dsn: "postgres://postgres:postgres@postgres:5432/neurousers"

api:
  port: 8834
  host: "0.0.0.0"
  url: "http://localhost:8834"
  jwt:
    secret: "CHANGE_ME_SHARED_JWT_SECRET"
    algorithm: "HS256"
    expire_seconds: 3600
    refresh_expire_days: 30
  bot:
    token: "REPLACE_WITH_REAL_BOT_TOKEN"
    name: "LidorubLoginBot"

auth:
  cors_origins:
    - "http://localhost:5173"
    - "http://localhost:5273"
    - "http://localhost:3000"
    - "http://localhost:8834"
  cookie_domain: null
  default_return_to: "http://localhost:5173/app"
