postgres:
  dsn: "postgres://postgres:postgres@postgres:5432/neurousers"

api:
  port: 8834
  host: "0.0.0.0"
  url: "http://localhost:8834"
  jwt:
    secret: "%0DK&B7jlxB!8T6lY"
    algorithm: "HS256"
    expire_seconds: 3600
    refresh_expire_days: 30
  bot:
    token: "7653458234:AAFLESK0Zoo4SbMI-Z8ZrF8HMQOLSsOOR_c"
    name: "MockBot"

auth:
  cors_origins:
    - "http://localhost:5173"
    - "http://localhost:5273"
    - "http://localhost:3000"
    - "http://localhost:8834"
  cookie_domain: null
  default_return_to: "http://localhost:5173/app"

internal:
  user_sync_token: "s70@dxw31Q6SbYVR2"
